In [7]:
import numpy as np
from sklearn.datasets import load_iris
import collections

from src import dataset, naiveBayes


SEED = 21318407
np.random.seed(seed=SEED)

In [8]:
features, target = load_iris(return_X_y=True)
shapeDS = (features.shape[0], features.shape[1]+1)
ds = np.zeros(shape=shapeDS)
ds[:, 0:-1] = features
ds[:, -1] = target

shuffle = np.random.permutation(shapeDS[0])
ds = ds[shuffle]

ds


array([[4.6, 3.1, 1.5, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [5.5, 2.5, 4. , 1.3, 1. ],
       [6.3, 2.8, 5.1, 1.5, 2. ],
       [5.7, 2.6, 3.5, 1. , 1. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [4.4, 3. , 1.3, 0.2, 0. ],
       [5.1, 2

In [9]:
ds = dataset.DataSetSKL()
X = ds.features[0:120]
y = ds.target[0:120]

testX = ds.features[121:]
testY = ds.target[121:]

nb = naiveBayes.NaiveBayesClassificator()
nb.fit(X, y)
mu_hat = nb.mu
sigma_hat = nb.sigma
predictions = nb.predict(testX)

print(mu_hat)
print(sigma_hat)
# print(f"predicted class: {predictions}")
# print(f" original class: {testY}")

[[5.52619048 2.92142857 3.49920635 1.10238095]
 [5.66097561 2.99268293 3.58455285 1.12926829]
 [6.27297297 3.31621622 3.97207207 1.25135135]]
[[1.58962579 0.91584756 0.96790548 0.31346305]
 [1.67330765 0.96102389 1.02041301 0.33011094]
 [2.06981982 1.17477477 1.26936937 0.40900901]]


In [10]:
for pstwo in nb.pstwa:
    print(pstwo)

[[0.00018928 0.00032601 0.00099552]]
[[2.39527283e-05 2.52693378e-05 2.45514166e-05]]
[[4.44920549e-05 4.47026480e-05 3.68948047e-05]]
[[6.68304752e-06 1.93450118e-05 2.78573373e-04]]
[[3.42506677e-05 3.38006170e-05 2.69280011e-05]]
[[0.01294485 0.01122888 0.00449954]]
[[0.01143144 0.00987635 0.00394008]]
[[0.00386368 0.00447979 0.00410697]]
[[0.01655307 0.01329469 0.00429774]]
[[3.18678610e-07 1.37364063e-06 6.62087906e-05]]
[[0.00014208 0.00026682 0.0010382 ]]
[[5.31322659e-05 5.14780351e-05 3.82050372e-05]]
[[0.00657743 0.00708554 0.00521121]]
[[0.0050305  0.00554519 0.00439142]]
[[0.00134706 0.00179452 0.00250434]]
[[1.97366511e-05 2.14678401e-05 2.28484452e-05]]
[[0.01336666 0.01218262 0.00555687]]
[[2.33592743e-06 7.44069862e-06 1.46321549e-04]]
[[1.97473764e-06 6.39971257e-06 1.32878904e-04]]
[[2.80319392e-08 1.54472997e-07 1.63435340e-05]]
[[1.43666653e-07 6.76552060e-07 4.31384588e-05]]
[[0.00019209 0.00033053 0.0010064 ]]
[[5.21606110e-05 5.91214879e-05 6.69284978e-05]]
[[0.0

In [11]:
print(list(testY))
print(list(predictions))

[2.0, 0.0, 0.0, 2.0, 0.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 0.0, 1.0, 0.0, 0.0, 2.0, 2.0, 2.0]
[2.0, 1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 2.0, 0.0, 1.0, 1.0, 2.0, 2.0, 0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 0.0, 1.0, 1.0, 2.0, 2.0, 2.0]


In [12]:
print(predictions)
p = predictions
print(f"0: {p[0]} | 1: {p[1]} | 2: {p[2]}")
print(f"p.argmax():   {p.argmax()}")
print(f"np.argmax(p): {np.argmax(p)}")


[2. 1. 1. 2. 0. 0. 0. 1. 0. 2. 2. 0. 1. 1. 2. 2. 0. 2. 2. 2. 2. 2. 2. 0.
 1. 1. 2. 2. 2.]
0: 2.0 | 1: 1.0 | 2: 1.0
p.argmax():   0
np.argmax(p): 0
