In [5]:
import numpy as np
from sklearn.datasets import load_iris
import collections

from src import dataset, naiveBayes

In [6]:
features, target = load_iris(return_X_y=True)
shapeDS = (features.shape[0], features.shape[1]+1)
ds = np.zeros(shape=shapeDS)
ds[:, 0:-1] = features
ds[:, -1] = target

shuffle = np.random.permutation(shapeDS[0])
ds = ds[shuffle]



In [7]:
ds = dataset.DataSetSKL()
X = ds.features[0:120]
y = ds.target[0:120]


nb = naiveBayes.NaiveBayesClassificator()
nb.fit(X, y)
mu_hat = nb.mu
sigma_hat = nb.sigma
print(mu_hat)
print(sigma_hat)
# mu_hat_sq = np.sqrt(mu_hat)
# print(mu_hat_sq)
# mu_hat_2 = np.power(mu_hat_sq, 2)
# print(mu_hat_2)

[[17.89487179  9.45641026 11.37948718  3.5974359 ]
 [17.89487179  9.45641026 11.37948718  3.5974359 ]
 [16.61666667  8.78095238 10.56666667  3.34047619]]
[[2.10804657 1.03114591 1.60266445 0.55113688]
 [2.10804657 1.03114591 1.60266445 0.55113688]
 [1.82983591 0.8872157  1.41597544 0.49045998]]


In [8]:
X[2, :]
l = int(list(set([0.0, 1.0, 2.0])))
l

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'