In [1]:
import numpy as np
from sklearn.datasets import load_iris
import collections

from src import dataset, naiveBayes


SEED = 9318407
np.random.seed(seed=SEED)

In [2]:
features, target = load_iris(return_X_y=True)
shapeDS = (features.shape[0], features.shape[1]+1)
ds = np.zeros(shape=shapeDS)
ds[:, 0:-1] = features
ds[:, -1] = target

shuffle = np.random.permutation(shapeDS[0])
ds = ds[shuffle]

ds


array([[6.5, 3. , 5.8, 2.2, 2. ],
       [5.4, 3. , 4.5, 1.5, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.2, 0. ],
       [6.1, 3. , 4.9, 1.8, 2. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [6.5, 3. , 5.5, 1.8, 2. ],
       [5.5, 2.5, 4. , 1.3, 1. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [4.8, 3. , 1.4, 0.3, 0. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.5, 2

In [3]:
ds = dataset.DataSetSKL()
X = ds.features[0:120]
y = ds.target[0:120]

testX = ds.features[121:]
testY = ds.target[121:]

nb = naiveBayes.NaiveBayesClassifier()
nb.fit(X, y)
mu_hat = nb.mu
sigma_hat = nb.sigma
predictions = nb.predict(testX)

print(mu_hat)
print(sigma_hat)

[[5.11407407 2.74740741 3.16296296 0.99851852]
 [6.5752381  3.53238095 4.06666667 1.28380952]
 [5.75333333 3.09083333 3.55833333 1.12333333]]
[[1.45361969 0.82044587 0.7521033  0.25561462]
 [2.40539016 1.33719897 1.32053911 0.43756639]
 [1.85108146 1.03642948 0.98879135 0.33146528]]
