In [1]:
import numpy as np
from sklearn.datasets import load_iris
import collections

from src import dataset, naiveBayes


SEED = 318407
np.random.seed(seed=SEED)

In [2]:
features, target = load_iris(return_X_y=True)
shapeDS = (features.shape[0], features.shape[1]+1)
ds = np.zeros(shape=shapeDS)
ds[:, 0:-1] = features
ds[:, -1] = target

shuffle = np.random.permutation(shapeDS[0])
ds = ds[shuffle]

ds


array([[6.4, 2.7, 5.3, 1.9, 2. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [6. , 3. , 4.8, 1.8, 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.2, 1.2, 0.2, 0. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [4.6, 3.2, 1.4, 0.2, 0. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [6.9, 3.1, 5.4, 2.1, 2. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [6.3, 2

In [3]:
ds = dataset.DataSetSKL()
X = ds.features[0:120]
y = ds.target[0:120]

testX = ds.features[121:]
testY = ds.target[121:]

nb = naiveBayes.NaiveBayesClassificator()
nb.fit(X, y)
mu_hat = nb.mu
sigma_hat = nb.sigma
print(f"\n mu:\n{mu_hat}")
print(f"\nsigma:\n{sigma_hat}\n")
print(f"shape: {len(testX[1].shape)}")
pstwo = nb.single_predict(testX[2])
print(testX[2], testY[2])
# print(pstwo)
# mu_hat_sq = np.sqrt(mu_hat)
# print(mu_hat_sq)
# mu_hat_2 = np.power(mu_hat_sq, 2)
# print(mu_hat_2)


 mu:
[[17.59        9.1925     11.3625      3.6225    ]
 [18.04102564  9.42820513 11.65384615  3.71538462]
 [17.16097561  8.96829268 11.08536585  3.53414634]]

sigma:
[[1.91993656 1.00760641 1.24299479 0.37189764]
 [2.01820086 1.05901471 1.30650637 0.39182712]
 [1.82795075 0.95948132 1.18354026 0.35324955]]

shape: 1
P: [[7.06123702e-10 2.48832637e-09 1.24034755e-08 3.64539211e-09]
 [1.10751731e-09 3.76075460e-09 1.68249394e-08 5.70453714e-09]
 [4.49837792e-10 1.64776942e-09 9.19316650e-09 2.32776325e-09]]
p: [[2.64822278e-35]
 [1.29922031e-34]
 [5.41949627e-36]]
max: 0
[5.6 3.  4.1 1.3] 1.0
[[2.64822278e-35]
 [1.29922031e-34]
 [5.41949627e-36]]


In [5]:
print(pstwo)
p = pstwo
print(f"0: {p[0]} | 1: {p[1]} | 2: {p[2]}")
print(f"p.argmax():   {p.argmax()}")
print(f"np.argmax(p): {np.argmax(p)}")


[[2.64822278e-35]
 [1.29922031e-34]
 [5.41949627e-36]]
0: [2.64822278e-35] | 1: [1.29922031e-34] | 2: [5.41949627e-36]


1